using System.Text;
using NexNet.PerformanceBenchmarks.Config;
using NexNet.PerformanceBenchmarks.Infrastructure;
using NexNet.PerformanceBenchmarks.Scenarios;

namespace NexNet.PerformanceBenchmarks.Reporting;

/// <summary>
/// Generates Markdown reports from benchmark runs.
/// </summary>
public sealed class MarkdownReporter
{
    /// <summary>
    /// Generates a Markdown report from a benchmark run.
    /// </summary>
    public static async Task WriteReportAsync(BenchmarkRun run, string outputPath, CancellationToken cancellationToken = default)
    {
        var markdown = GenerateReport(run);
        await File.WriteAllTextAsync(outputPath, markdown, cancellationToken);
    }

    /// <summary>
    /// Generates a Markdown string from a benchmark run.
    /// </summary>
    public static string GenerateReport(BenchmarkRun run)
    {
        var sb = new StringBuilder();

        // Header
        var shortHash = run.CommitHash != null && run.CommitHash.Length > 7
            ? run.CommitHash[..7]
            : run.CommitHash ?? "local";

        sb.AppendLine($"# Benchmark Results - {shortHash}");
        sb.AppendLine();

        // Metadata
        if (!string.IsNullOrEmpty(run.CommitHash))
        {
            sb.AppendLine($"**Commit**: {run.CommitHash}");
            if (!string.IsNullOrEmpty(run.CommitMessage))
                sb.AppendLine($"**Message**: {run.CommitMessage}");
            if (!string.IsNullOrEmpty(run.Branch))
                sb.AppendLine($"**Branch**: {run.Branch}");
        }
        sb.AppendLine($"**Date**: {run.StartTime:yyyy-MM-dd HH:mm:ss} UTC");
        sb.AppendLine($"**Duration**: {FormatDuration(run.Duration)}");
        sb.AppendLine($"**Runtime**: {run.RuntimeVersion}");
        sb.AppendLine($"**OS**: {run.OSDescription}");
        sb.AppendLine($"**Processors**: {Environment.ProcessorCount}");
        sb.AppendLine();

        // Summary
        var successCount = run.Results.Count(r => r.Success);
        var failCount = run.Results.Count(r => !r.Success);
        sb.AppendLine("## Summary");
        sb.AppendLine();
        sb.AppendLine($"- **Total Scenarios**: {run.Results.Count}");
        sb.AppendLine($"- **Passed**: {successCount}");
        sb.AppendLine($"- **Failed**: {failCount}");
        sb.AppendLine();

        // Results by category
        var byCategory = run.Results
            .GroupBy(r => r.Category)
            .OrderBy(g => g.Key);

        foreach (var categoryGroup in byCategory)
        {
            sb.AppendLine($"## {categoryGroup.Key} Benchmarks");
            sb.AppendLine();

            switch (categoryGroup.Key)
            {
                case BenchmarkCategory.Latency:
                    WriteLatencyTable(sb, categoryGroup.ToList());
                    break;
                case BenchmarkCategory.Throughput:
                    WriteThroughputTable(sb, categoryGroup.ToList());
                    break;
                case BenchmarkCategory.Scalability:
                    WriteScalabilityTable(sb, categoryGroup.ToList());
                    break;
                case BenchmarkCategory.Stress:
                    WriteStressTable(sb, categoryGroup.ToList());
                    break;
                case BenchmarkCategory.Collections:
                    WriteCollectionsTable(sb, categoryGroup.ToList());
                    break;
                case BenchmarkCategory.Overhead:
                    WriteOverheadTable(sb, categoryGroup.ToList());
                    break;
            }

            sb.AppendLine();
        }

        // Transport comparison (for latency)
        var latencyResults = run.Results
            .Where(r => r.Category == BenchmarkCategory.Latency && r.LatencyMetrics != null && r.Success)
            .ToList();

        if (latencyResults.Count > 0)
        {
            sb.AppendLine("## Transport Comparison (Latency P50)");
            sb.AppendLine();
            WriteTransportComparisonTable(sb, latencyResults);
            sb.AppendLine();
        }

        // Failures
        var failures = run.Results.Where(r => !r.Success).ToList();
        if (failures.Count > 0)
        {
            sb.AppendLine("## Failures");
            sb.AppendLine();
            foreach (var failure in failures)
            {
                sb.AppendLine($"- **{failure.ScenarioName}** [{failure.Transport}]");
                if (!string.IsNullOrEmpty(failure.ErrorMessage))
                    sb.AppendLine($"  - {failure.ErrorMessage}");
            }
            sb.AppendLine();
        }

        // Footer
        sb.AppendLine("---");
        sb.AppendLine();
        sb.AppendLine("*Generated by NexNet Performance Benchmark Suite*");

        return sb.ToString();
    }

    private static void WriteLatencyTable(StringBuilder sb, List<ScenarioResult> results)
    {
        sb.AppendLine("| Scenario | Transport | Payload | P50 (μs) | P95 (μs) | P99 (μs) | Mean (μs) | StdDev |");
        sb.AppendLine("|----------|-----------|---------|----------|----------|----------|-----------|--------|");

        foreach (var result in results.OrderBy(r => r.ScenarioName).ThenBy(r => r.Transport).ThenBy(r => r.PayloadSize))
        {
            var payload = result.PayloadSize?.ToString() ?? "-";
            if (!result.Success)
            {
                sb.AppendLine($"| {result.ScenarioName} | {result.Transport} | {payload} | FAILED | - | - | - | - |");
                continue;
            }

            var m = result.LatencyMetrics;
            if (m == null)
            {
                sb.AppendLine($"| {result.ScenarioName} | {result.Transport} | {payload} | N/A | - | - | - | - |");
                continue;
            }

            sb.AppendLine($"| {result.ScenarioName} | {result.Transport} | {payload} | " +
                         $"{m.P50Microseconds:F1} | {m.P95Microseconds:F1} | {m.P99Microseconds:F1} | " +
                         $"{m.MeanMicroseconds:F1} | {m.StdDevMicroseconds:F1} |");
        }
    }

    private static void WriteThroughputTable(StringBuilder sb, List<ScenarioResult> results)
    {
        sb.AppendLine("| Scenario | Transport | Payload | Rate | Unit | Total Bytes | Duration |");
        sb.AppendLine("|----------|-----------|---------|------|------|-------------|----------|");

        foreach (var result in results.OrderBy(r => r.ScenarioName).ThenBy(r => r.Transport).ThenBy(r => r.PayloadSize))
        {
            var payload = result.PayloadSize?.ToString() ?? "-";
            if (!result.Success)
            {
                sb.AppendLine($"| {result.ScenarioName} | {result.Transport} | {payload} | FAILED | - | - | - |");
                continue;
            }

            var m = result.ThroughputMetrics;
            if (m == null)
            {
                sb.AppendLine($"| {result.ScenarioName} | {result.Transport} | {payload} | N/A | - | - | - |");
                continue;
            }

            string rate, unit;
            if (m.MegabytesPerSecond > 0.01)
            {
                rate = $"{m.MegabytesPerSecond:F2}";
                unit = "MB/s";
            }
            else if (m.OperationsPerSecond > 0)
            {
                rate = $"{m.OperationsPerSecond:F0}";
                unit = "ops/s";
            }
            else
            {
                rate = $"{m.MessagesPerSecond:F0}";
                unit = "msg/s";
            }

            sb.AppendLine($"| {result.ScenarioName} | {result.Transport} | {payload} | " +
                         $"{rate} | {unit} | {FormatBytes(m.TotalBytes)} | {m.Duration.TotalSeconds:F1}s |");
        }
    }

    private static void WriteScalabilityTable(StringBuilder sb, List<ScenarioResult> results)
    {
        sb.AppendLine("| Scenario | Transport | Clients | P50 (μs) | P95 (μs) | Spread (μs) | Status |");
        sb.AppendLine("|----------|-----------|---------|----------|----------|-------------|--------|");

        foreach (var result in results.OrderBy(r => r.ScenarioName).ThenBy(r => r.Transport))
        {
            if (!result.Success)
            {
                sb.AppendLine($"| {result.ScenarioName} | {result.Transport} | - | FAILED | - | - | - |");
                continue;
            }

            var m = result.ScalabilityMetrics;
            if (m == null)
            {
                sb.AppendLine($"| {result.ScenarioName} | {result.Transport} | - | N/A | - | - | - |");
                continue;
            }

            var p50 = m.PerClientLatency?.P50Microseconds ?? 0;
            var p95 = m.PerClientLatency?.P95Microseconds ?? 0;

            sb.AppendLine($"| {result.ScenarioName} | {result.Transport} | {m.ClientCount} | " +
                         $"{p50:F1} | {p95:F1} | {m.DeliverySpreadMicroseconds:F1} | OK |");
        }
    }

    private static void WriteStressTable(StringBuilder sb, List<ScenarioResult> results)
    {
        sb.AppendLine("| Scenario | Transport | Operations | Ops/s | Duration | Errors | Status |");
        sb.AppendLine("|----------|-----------|------------|-------|----------|--------|--------|");

        foreach (var result in results.OrderBy(r => r.ScenarioName).ThenBy(r => r.Transport))
        {
            if (!result.Success)
            {
                sb.AppendLine($"| {result.ScenarioName} | {result.Transport} | - | - | - | - | FAILED |");
                continue;
            }

            var m = result.StressMetrics;
            if (m == null)
            {
                sb.AppendLine($"| {result.ScenarioName} | {result.Transport} | - | - | - | - | N/A |");
                continue;
            }

            var status = m.ErrorCount > 0 ? $"{m.ErrorCount} errors" : "OK";

            sb.AppendLine($"| {result.ScenarioName} | {result.Transport} | {m.TotalOperations:N0} | " +
                         $"{m.OperationsPerSecond:F1} | {m.Duration.TotalSeconds:F1}s | {m.ErrorCount} | {status} |");
        }
    }

    private static void WriteCollectionsTable(StringBuilder sb, List<ScenarioResult> results)
    {
        sb.AppendLine("| Scenario | Transport | Items | Sync Time (ms) | Ops/s | Duration | Status |");
        sb.AppendLine("|----------|-----------|-------|----------------|-------|----------|--------|");

        foreach (var result in results.OrderBy(r => r.ScenarioName).ThenBy(r => r.Transport))
        {
            if (!result.Success)
            {
                sb.AppendLine($"| {result.ScenarioName} | {result.Transport} | - | - | - | - | FAILED |");
                continue;
            }

            var m = result.CollectionMetrics;
            if (m == null)
            {
                sb.AppendLine($"| {result.ScenarioName} | {result.Transport} | - | - | - | - | N/A |");
                continue;
            }

            var syncTime = m.SyncTimeMs > 0 ? $"{m.SyncTimeMs:F1}" : "-";
            var opsPerSec = m.OperationsPerSecond > 0 ? $"{m.OperationsPerSecond:F0}" : "-";

            sb.AppendLine($"| {result.ScenarioName} | {result.Transport} | {m.ItemCount:N0} | " +
                         $"{syncTime} | {opsPerSec} | {m.Duration.TotalSeconds:F1}s | OK |");
        }
    }

    private static void WriteOverheadTable(StringBuilder sb, List<ScenarioResult> results)
    {
        sb.AppendLine("| Scenario | Transport | P50 (μs) | P95 (μs) | Details |");
        sb.AppendLine("|----------|-----------|----------|----------|---------|");

        foreach (var result in results.OrderBy(r => r.ScenarioName).ThenBy(r => r.Transport))
        {
            if (!result.Success)
            {
                sb.AppendLine($"| {result.ScenarioName} | {result.Transport} | FAILED | - | {result.ErrorMessage ?? "-"} |");
                continue;
            }

            // Latency-based overhead (CancellationOverhead)
            if (result.LatencyMetrics != null)
            {
                var m = result.LatencyMetrics;
                var details = GetCustomMetricsDetails(result.CustomMetrics);
                sb.AppendLine($"| {result.ScenarioName} | {result.Transport} | {m.P50Microseconds:F1} | {m.P95Microseconds:F1} | {details} |");
            }
            // Stress-based overhead (Reconnection)
            else if (result.StressMetrics != null)
            {
                var m = result.StressMetrics;
                var details = $"Success: {m.TotalOperations - m.ErrorCount}/{m.TotalOperations}";
                if (result.CustomMetrics?.TryGetValue("Reconnect_Mean_ms", out var meanMs) == true)
                {
                    details = $"Reconnect: {meanMs:F1}ms";
                }
                sb.AppendLine($"| {result.ScenarioName} | {result.Transport} | - | - | {details} |");
            }
            else
            {
                sb.AppendLine($"| {result.ScenarioName} | {result.Transport} | - | - | OK |");
            }
        }
    }

    private static void WriteTransportComparisonTable(StringBuilder sb, List<ScenarioResult> results)
    {
        // Get all unique scenarios and transports
        var scenarios = results.Select(r => r.ScenarioName).Distinct().OrderBy(n => n).ToList();
        var transports = results.Select(r => r.Transport).Distinct().OrderBy(t => t).ToList();

        // Header
        sb.Append("| Scenario |");
        foreach (var transport in transports)
        {
            sb.Append($" {transport} |");
        }
        sb.AppendLine();

        // Separator
        sb.Append("|----------|");
        foreach (var _ in transports)
        {
            sb.Append("--------|");
        }
        sb.AppendLine();

        // Data rows
        foreach (var scenario in scenarios)
        {
            sb.Append($"| {scenario} |");
            foreach (var transport in transports)
            {
                var result = results.FirstOrDefault(r => r.ScenarioName == scenario && r.Transport == transport);
                var value = result?.LatencyMetrics?.P50Microseconds;
                sb.Append(value.HasValue ? $" {value.Value:F1}μs |" : " - |");
            }
            sb.AppendLine();
        }
    }

    private static string GetCustomMetricsDetails(Dictionary<string, object>? customMetrics)
    {
        if (customMetrics == null) return "-";

        if (customMetrics.TryGetValue("Overhead_Percent", out var overheadPercent))
        {
            return $"Overhead: {overheadPercent:F1}%";
        }

        return "-";
    }

    private static string FormatDuration(TimeSpan duration)
    {
        if (duration.TotalHours >= 1)
            return $"{(int)duration.TotalHours}h {duration.Minutes}m {duration.Seconds}s";
        if (duration.TotalMinutes >= 1)
            return $"{(int)duration.TotalMinutes}m {duration.Seconds}s";
        return $"{duration.TotalSeconds:F1}s";
    }

    private static string FormatBytes(long bytes)
    {
        if (bytes >= 1024L * 1024L * 1024L)
            return $"{bytes / (1024.0 * 1024.0 * 1024.0):F2} GB";
        if (bytes >= 1024 * 1024)
            return $"{bytes / (1024.0 * 1024.0):F2} MB";
        if (bytes >= 1024)
            return $"{bytes / 1024.0:F1} KB";
        return $"{bytes} B";
    }
}
