using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using NexNet.Generator.Emission;
using NexNet.Generator.Extraction;
using NexNet.Generator.Models;
using NexNet.Generator.Serialization;
using NexNet.Generator.Validation;

namespace NexNet.Generator;

/// <summary>
/// Payload serializer backend selected by the <c>NexNetSerializer</c> MSBuild property.
/// </summary>
internal enum SerializerBackend
{
    MessagePack,
    MemoryPack
}

[Generator(LanguageNames.CSharp)]
internal partial class NexusGenerator : IIncrementalGenerator
{
    public const string NexusAttributeFullName = "NexNet.NexusAttribute`2";
    public const string NexusObjectAttributeFullName = "NexNet.Serialization.NexusObjectAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        // TRANSFORM PHASE: Extract all data here - this is cached by the incremental pipeline
        // The transform runs during semantic analysis and extracts all data into equatable records.
        // When the extracted data hasn't changed, the output phase is skipped entirely.
        var nexusData = context.SyntaxProvider.ForAttributeWithMetadataName(
            NexusAttributeFullName,
            predicate: static (node, _) => node is ClassDeclarationSyntax,
            transform: static (ctx, ct) => NexusDataExtractor.Extract(ctx, ct))
            .Where(static data => data is not null)!;

        var parseOptions = context.ParseOptionsProvider.Select(static (opts, _) =>
            ((CSharpParseOptions)opts).LanguageVersion);

        var backend = context.AnalyzerConfigOptionsProvider.Select(static (provider, _) =>
            provider.GlobalOptions.TryGetValue("build_property.NexNetSerializer", out var value)
            && string.Equals(value, "MemoryPack", StringComparison.OrdinalIgnoreCase)
                ? SerializerBackend.MemoryPack
                : SerializerBackend.MessagePack);

        // Combine with language version only (NOT full compilation)
        // This is the key change - we no longer depend on CompilationProvider
        // which changes on every keystroke in any file.
        var source = nexusData.Combine(parseOptions).Combine(backend);

        // OUTPUT PHASE: Use only extracted data - no semantic model access
        // This phase only runs when the extracted data actually changes.
        context.RegisterSourceOutput(source, static (ctx, source) =>
        {
            var ((data, langVersion), serializerBackend) = source;
            Generate(data!, langVersion, serializerBackend, ctx);
        });

        // Formatters for [NexusObject] types declared in this compilation, so types used only at runtime
        // (e.g. CreateChannel<T>()) are registered even when no nexus references them.
        var nexusObjects = context.SyntaxProvider.ForAttributeWithMetadataName(
            NexusObjectAttributeFullName,
            predicate: static (node, _) => node is TypeDeclarationSyntax,
            transform: static (ctx, _) => ExtractNexusObject(ctx))
            .Where(static data => data is not null)
            .Combine(backend);

        context.RegisterSourceOutput(nexusObjects, static (ctx, source) =>
        {
            var (data, serializerBackend) = source;
            if (serializerBackend != SerializerBackend.MessagePack || data == null)
                return;

            ReportSerializationDiagnostics(data.Diagnostics, ctx);
            if (data.Code.Length > 0)
                ctx.AddSource($"{data.FileName}.NexusFormatter.g.cs", "// <auto-generated/>\n" + data.Code);
        });

        // Assembly level [NexusSerializable<T>] and [NexusFormatter<TFormatter, T>] declarations.
        var assemblyDeclarations = context.CompilationProvider
            .Select(static (compilation, _) =>
            {
                var builder = new SerializationBuilder(compilation, "assembly");
                builder.AddAssemblyDeclaredRoots();
                return new SerializationOutput("NexNetAssembly", builder.Build(), builder.Diagnostics.ToArray());
            })
            .Combine(backend);

        context.RegisterSourceOutput(assemblyDeclarations, static (ctx, source) =>
        {
            var (data, serializerBackend) = source;
            if (serializerBackend != SerializerBackend.MessagePack)
                return;

            ReportSerializationDiagnostics(data.Diagnostics, ctx);
            if (data.Code.Length > 0)
                ctx.AddSource("NexNet.AssemblySerialization.g.cs", "// <auto-generated/>\n" + data.Code);
        });
    }

    private sealed record SerializationOutput(string FileName, string Code, SerializationDiagnostic[] Diagnostics)
    {
        public bool Equals(SerializationOutput? other)
            => other != null && FileName == other.FileName && Code == other.Code && Diagnostics.SequenceEqual(other.Diagnostics);

        public override int GetHashCode() => Code.GetHashCode();
    }

    private static SerializationOutput? ExtractNexusObject(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol symbol || symbol.IsGenericType)
            return null;

        var fileName = SerializationBuilder.MetadataFullName(symbol).Replace('+', '.').Replace('`', '_');
        var builder = new SerializationBuilder(ctx.SemanticModel.Compilation, ((uint)new XxHash32().ComputeHash(System.Text.Encoding.UTF8.GetBytes(fileName))).ToString("x8"));
        builder.Require(symbol, symbol.Name, LocationData.FromSymbol(symbol));
        return new SerializationOutput(fileName, builder.Build(), builder.Diagnostics.ToArray());
    }

    private static void ReportSerializationDiagnostics(IEnumerable<SerializationDiagnostic> diagnostics, SourceProductionContext context)
    {
        foreach (var diag in diagnostics)
        {
            var descriptor = DiagnosticDescriptors.FindSerializationDescriptor(diag.Id);
            if (descriptor != null)
                context.ReportDiagnostic(Diagnostic.Create(descriptor, Location.None, diag.Arg0, diag.Arg1));
        }
    }

    private static void Generate(
        NexusGenerationData data,
        LanguageVersion langVersion,
        SerializerBackend backend,
        SourceProductionContext context)
    {
        // Validate using cached data (no ISymbol references)
        var diagnostics = NexusValidator.Validate(data, context.CancellationToken);

        bool hasBlockingErrors = false;
        foreach (var diagnostic in diagnostics)
        {
            context.ReportDiagnostic(diagnostic);
            // HashLock mismatch is an error but shouldn't block generation
            if (diagnostic.Severity == DiagnosticSeverity.Error &&
                diagnostic.Id != DiagnosticDescriptors.VersionHashLockMismatch.Id)
            {
                hasBlockingErrors = true;
            }
        }

        if (backend == SerializerBackend.MessagePack)
        {
            ReportSerializationDiagnostics(data.SerializationDiagnostics, context);
            if (data.SerializationDiagnostics.Any(d => d.Id != "NEXNET037"))
                hasBlockingErrors = true;
        }

        if (hasBlockingErrors)
            return;

        // Generate code using cached data
        var sb = SymbolUtilities.GetStringBuilder();

        sb.AppendLine(@"// <auto-generated/>
#nullable enable
");

        var code = NexusEmitter.Emit(data, langVersion, backend);
        sb.Append(code);

        if (backend == SerializerBackend.MessagePack)
            sb.Append(data.SerializationCode);

        var finalCode = sb.ToString();
        SymbolUtilities.ReturnStringBuilder(sb);

        context.AddSource($"{data.FullTypeName}.Nexus.g.cs", finalCode);
    }
}
